# Generated by Django 3.0.8 on 2020-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_auto_20200711_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpost',
            name='course',
            field=models.CharField(choices=[('', 'SELECT-COURSE'), ('bca', 'BCA'), ('bba', 'BBA'), ('bcom', 'B.COM'), ('cs', 'BSc.CS'), ('ft', 'BSc.FT'), ('mb', 'BSc.MB'), ('bt', 'BSc.BT'), ('eco', 'Ba.ECO'), ('if', 'Ba.IF')], default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='classpost',
            name='subject',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='classpost',
            name='year',
            field=models.CharField(choices=[('', 'SELECT-YEAR'), ('1', 'FIRST-YEAR'), ('2', 'SECOND-YEAR'), ('3', 'THIRD-YEAR')], default=None, max_length=6),
        ),
    ]
