# Generated by Django 3.0.8 on 2020-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0006_auto_20200711_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpost',
            name='link',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
